#!/usr/bin/env python3
"""Generate a coddog `decomp.yaml` for one blob (or the exe).

coddog's match/cluster/submatch commands use the project in the current
directory (`scan_for_config`: nearest decomp.yaml upward from cwd), and
compare2/compare-n/compare-raw take explicit yaml paths. The repo root
decomp.yaml describes only the exe, so blobs were invisible to coddog.
This script stamps a minimal config pointing at the blob's own ELF + map
+ asm tree; the `tools/coddog` wrapper calls it for `--blob` runs.

Single source of truth is tools/scripts/target.py (no committed outputs;
regenerated on every wrapper run, so `make clean` wiping build/ is safe).
All paths are absolute so the config works regardless of cwd.

Usage: coddog_yaml.py <blob>   (empty/"exe" = exe; prints yaml path)
Requires `make BLOB=<blob> build` to have run at least once (ELF must
exist: coddog reads function bytes + sizes from it, decompiled-ness from
stub-file stems under the asm tree, mirroring the exe flow).
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import target as _target_mod

ROOT = _target_mod.ROOT
ROOT_DECOMP_YAML = str(ROOT / "decomp.yaml")


def main() -> int:
    name = sys.argv[1] if len(sys.argv) > 1 else ""
    if name in ("", "exe"):
        print(ROOT_DECOMP_YAML)
        return 0
    t = _target_mod.get_target(name)
    if not t.yaml.is_file():
        print(f"coddog_yaml: no such blob: {name} ({t.yaml} missing)",
              file=sys.stderr)
        return 1
    if not t.out_elf.is_file():
        print(f"coddog_yaml: {t.out_elf} missing; "
              f"run `make BLOB={name} build` first", file=sys.stderr)
        return 1
    label = t.family or name
    # Absolute throughout: coddog joins relative paths onto the yaml's
    # directory (the build dir), which would misresolve repo-relative ones.
    abspath = lambda p: p if p.is_absolute() else ROOT / p
    text = (
        f"# Generated by tools/scripts/coddog_yaml.py {name}; do not edit.\n"
        f"# Lets coddog match/cluster/submatch see this blob's symbols\n"
        f"# (repo-root decomp.yaml covers the exe only).\n"
        f"name: FFT {label} {t.src_units[0] if t.src_units else name}\n"
        f"platform: psx\n"
        f"versions:\n"
        f"- name: {name}\n"
        f"  fullname: \"{name}\"\n"
        f"  paths:\n"
        f"    target: \"{abspath(t.oracle)}\"\n"
        f"    build_dir: \"{abspath(t.build)}\"\n"
        f"    map: \"{abspath(t.map)}\"\n"
        f"    compiled_target: \"{abspath(t.out_bin)}\"\n"
        f"    elf: \"{abspath(t.out_elf)}\"\n"
        f"    asm: \"{abspath(t.asm_root)}\"\n"
    )
    out = t.build / "decomp.yaml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    print(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
