name: E007.BIN
sha1: b3baa23fe5c1894d5f2d9774173414b6f53d2621
options:
  basename: E007.BIN
  target_path: rom/extracted/baserom/EFFECT/E007.BIN
  elf_path: build/blobs/effect_E007/effect_E007.elf
  base_path: ../../..
  platform: psx
  compiler: PSYQ

  asm_path: rom/extracted/blobs/effect
  src_path: src/blobs/effect
  build_path: build/blobs/effect_E007

  ld_script_path: build/blobs/effect_E007/effect_E007.ld
  ld_dependencies: True
  ld_align_section_vram_end: False

  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/blobs/effect/E007.symbols.txt

  undefined_funcs_auto_path: build/blobs/effect_E007/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/blobs/effect_E007/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

family: effect

segments:
  - name: E007
    type: code
    align: 0
    start: 0x0
    vram: 0x801C2500
    subsegments:
      - [0x0, c, E007]

  - name: E007_data
    type: data
    align: 0
    start: 0x14F8
    vram: 0x801C39F8
    subsegments:
      - [0x14F8, data, E007_data]

  - [0xD414]
