name: E071.BIN
sha1: 516a122bbbc169762e9a274de6704128579618c9
options:
  basename: E071.BIN
  target_path: rom/extracted/baserom/EFFECT/E071.BIN
  elf_path: build/blobs/effect_E071/effect_E071.elf
  base_path: ../../..
  platform: psx
  compiler: PSYQ

  asm_path: rom/extracted/blobs/effect
  src_path: src/blobs/effect
  build_path: build/blobs/effect_E071

  ld_script_path: build/blobs/effect_E071/effect_E071.ld
  ld_dependencies: True
  ld_align_section_vram_end: False

  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/blobs/effect/E071.symbols.txt

  undefined_funcs_auto_path: build/blobs/effect_E071/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/blobs/effect_E071/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

family: effect

segments:
  - name: E071
    type: code
    align: 0
    start: 0x0
    vram: 0x801C2500
    subsegments:
      - [0x0, c, E071]

  - name: E071_data
    type: data
    align: 0
    start: 0x1A74
    vram: 0x801C3F74
    subsegments:
      - [0x1A74, data, E071_data]

  - [0x165E4]
