name: E092.BIN
sha1: 9187c98311aca0430d0b16307cd446906faae446
options:
  basename: E092.BIN
  target_path: rom/extracted/baserom/EFFECT/E092.BIN
  elf_path: build/blobs/effect_E092/effect_E092.elf
  base_path: ../../..
  platform: psx
  compiler: PSYQ

  asm_path: rom/extracted/blobs/effect
  src_path: src/blobs/effect
  build_path: build/blobs/effect_E092

  ld_script_path: build/blobs/effect_E092/effect_E092.ld
  ld_dependencies: True
  ld_align_section_vram_end: False

  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/blobs/effect/E092.symbols.txt

  undefined_funcs_auto_path: build/blobs/effect_E092/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/blobs/effect_E092/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

family: effect

segments:
  - name: E092
    type: code
    align: 0
    start: 0x0
    vram: 0x801C2500
    subsegments:
      - [0x0, c, E092]

  - name: E092_data
    type: data
    align: 0
    start: 0x15D0
    vram: 0x801C3AD0
    subsegments:
      - [0x15D0, data, E092_data]

  - [0xCEE4]
