name: E161.BIN
sha1: a9a12ede713fb0cca8c7f927efd8b324ce23941d
options:
  basename: E161.BIN
  target_path: rom/extracted/baserom/EFFECT/E161.BIN
  elf_path: build/blobs/effect_E161/effect_E161.elf
  base_path: ../../..
  platform: psx
  compiler: PSYQ

  asm_path: rom/extracted/blobs/effect
  src_path: src/blobs/effect
  build_path: build/blobs/effect_E161

  ld_script_path: build/blobs/effect_E161/effect_E161.ld
  ld_dependencies: True
  ld_align_section_vram_end: False

  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/blobs/effect/E161.symbols.txt

  undefined_funcs_auto_path: build/blobs/effect_E161/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/blobs/effect_E161/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

family: effect

segments:
  - name: E161
    type: code
    align: 0
    start: 0x0
    vram: 0x801C2500
    subsegments:
      - [0x0, c, E161]

  - name: E161_data
    type: data
    align: 0
    start: 0x15F8
    vram: 0x801C3AF8
    subsegments:
      - [0x15F8, data, E161_data]

  - [0xC888]
