name: E235.BIN
sha1: 06f2d2c308db500b74ef8cc4b3bd9437ac93e5a0
options:
  basename: E235.BIN
  target_path: rom/extracted/baserom/EFFECT/E235.BIN
  elf_path: build/blobs/effect_E235/effect_E235.elf
  base_path: ../../..
  platform: psx
  compiler: PSYQ

  asm_path: rom/extracted/blobs/effect
  src_path: src/blobs/effect
  build_path: build/blobs/effect_E235

  ld_script_path: build/blobs/effect_E235/effect_E235.ld
  ld_dependencies: True
  ld_align_section_vram_end: False

  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/blobs/effect/E235.symbols.txt

  undefined_funcs_auto_path: build/blobs/effect_E235/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/blobs/effect_E235/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

family: effect

segments:
  - name: E235
    type: code
    align: 0
    start: 0x0
    vram: 0x801C2500
    subsegments:
      - [0x0, c, E235]

  - name: E235_data
    type: data
    align: 0
    start: 0x1D44
    vram: 0x801C4244
    subsegments:
      - [0x1D44, data, E235_data]

  - [0x15514]
