name: E236.BIN
sha1: 777ed5ca476766b036d2ebe3fff7b346a4022c3d
options:
  basename: E236.BIN
  target_path: rom/extracted/baserom/EFFECT/E236.BIN
  elf_path: build/blobs/effect_E236/effect_E236.elf
  base_path: ../../..
  platform: psx
  compiler: PSYQ

  asm_path: rom/extracted/blobs/effect
  src_path: src/blobs/effect
  build_path: build/blobs/effect_E236

  ld_script_path: build/blobs/effect_E236/effect_E236.ld
  ld_dependencies: True
  ld_align_section_vram_end: False

  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/blobs/effect/E236.symbols.txt

  undefined_funcs_auto_path: build/blobs/effect_E236/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/blobs/effect_E236/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

family: effect

segments:
  - name: E236
    type: code
    align: 0
    start: 0x0
    vram: 0x801C2500
    subsegments:
      - [0x0, c, E236]

  - name: E236_data
    type: data
    align: 0
    start: 0x774
    vram: 0x801C2C74
    subsegments:
      - [0x774, data, E236_data]

  - [0x14410]
