name: E240.BIN
sha1: 58a01144a57e3ebccaeeeec132f89053eda6c011
options:
  basename: E240.BIN
  target_path: rom/extracted/baserom/EFFECT/E240.BIN
  elf_path: build/blobs/effect_E240/effect_E240.elf
  base_path: ../../..
  platform: psx
  compiler: PSYQ

  asm_path: rom/extracted/blobs/effect
  src_path: src/blobs/effect
  build_path: build/blobs/effect_E240

  ld_script_path: build/blobs/effect_E240/effect_E240.ld
  ld_dependencies: True
  ld_align_section_vram_end: False

  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/blobs/effect/E240.symbols.txt

  undefined_funcs_auto_path: build/blobs/effect_E240/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/blobs/effect_E240/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

family: effect

segments:
  - name: E240
    type: code
    align: 0
    start: 0x0
    vram: 0x801C2500
    subsegments:
      - [0x0, c, E240]

  - name: E240_data
    type: data
    align: 0
    start: 0x177C
    vram: 0x801C3C7C
    subsegments:
      - [0x177C, data, E240_data]

  - [0x15C68]
