name: E259.BIN
sha1: d0ed0ba8cdccc9f6dea5f281937268f25e7e877e
options:
  basename: E259.BIN
  target_path: rom/extracted/baserom/EFFECT/E259.BIN
  elf_path: build/blobs/effect_E259/effect_E259.elf
  base_path: ../../..
  platform: psx
  compiler: PSYQ

  asm_path: rom/extracted/blobs/effect
  src_path: src/blobs/effect
  build_path: build/blobs/effect_E259

  ld_script_path: build/blobs/effect_E259/effect_E259.ld
  ld_dependencies: True
  ld_align_section_vram_end: False

  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/blobs/effect/E259.symbols.txt

  undefined_funcs_auto_path: build/blobs/effect_E259/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/blobs/effect_E259/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

family: effect

segments:
  - name: E259
    type: code
    align: 0
    start: 0x0
    vram: 0x801C2500
    subsegments:
      - [0x0, c, E259]

  - name: E259_data
    type: data
    align: 0
    start: 0x27F8
    vram: 0x801C4CF8
    subsegments:
      - [0x27F8, data, E259_data]

  - [0x16EDC]
