name: E341.BIN
sha1: 47b1c67b589a90941e56c3eb7956c970673bf596
options:
  basename: E341.BIN
  target_path: rom/extracted/baserom/EFFECT/E341.BIN
  elf_path: build/blobs/effect_E341/effect_E341.elf
  base_path: ../../..
  platform: psx
  compiler: PSYQ

  asm_path: rom/extracted/blobs/effect
  src_path: src/blobs/effect
  build_path: build/blobs/effect_E341

  ld_script_path: build/blobs/effect_E341/effect_E341.ld
  ld_dependencies: True
  ld_align_section_vram_end: False

  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/blobs/effect/E341.symbols.txt

  undefined_funcs_auto_path: build/blobs/effect_E341/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/blobs/effect_E341/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

family: effect

segments:
  - name: E341
    type: code
    align: 0
    start: 0x0
    vram: 0x801C2500
    subsegments:
      - [0x0, c, E341]

  - name: E341_data
    type: data
    align: 0
    start: 0x1710
    vram: 0x801C3C10
    subsegments:
      - [0x1710, data, E341_data]

  - [0x854C]
