name: E355.BIN
sha1: f0d0f26cacbdb792b893984c0b042ba497839067
options:
  basename: E355.BIN
  target_path: rom/extracted/baserom/EFFECT/E355.BIN
  elf_path: build/blobs/effect_E355/effect_E355.elf
  base_path: ../../..
  platform: psx
  compiler: PSYQ

  asm_path: rom/extracted/blobs/effect
  src_path: src/blobs/effect
  build_path: build/blobs/effect_E355

  ld_script_path: build/blobs/effect_E355/effect_E355.ld
  ld_dependencies: True
  ld_align_section_vram_end: False

  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/blobs/effect/E355.symbols.txt

  undefined_funcs_auto_path: build/blobs/effect_E355/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/blobs/effect_E355/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

family: effect

segments:
  - name: E355
    type: code
    align: 0
    start: 0x0
    vram: 0x801C2500
    subsegments:
      - [0x0, c, E355]

  - name: E355_data
    type: data
    align: 0
    start: 0x1FA0
    vram: 0x801C44A0
    subsegments:
      - [0x1FA0, data, E355_data]

  - [0xD0A8]
