name: E376.BIN
sha1: 87c9e43c1d79c4e5f9e7742deed6e5a0f7a8e96e
options:
  basename: E376.BIN
  target_path: rom/extracted/baserom/EFFECT/E376.BIN
  elf_path: build/blobs/effect_E376/effect_E376.elf
  base_path: ../../..
  platform: psx
  compiler: PSYQ

  asm_path: rom/extracted/blobs/effect
  src_path: src/blobs/effect
  build_path: build/blobs/effect_E376

  ld_script_path: build/blobs/effect_E376/effect_E376.ld
  ld_dependencies: True
  ld_align_section_vram_end: False

  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/blobs/effect/E376.symbols.txt

  undefined_funcs_auto_path: build/blobs/effect_E376/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/blobs/effect_E376/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

family: effect

segments:
  - name: E376
    type: code
    align: 0
    start: 0x0
    vram: 0x801C2500
    subsegments:
      - [0x0, c, E376]

  - name: E376_data
    type: data
    align: 0
    start: 0x21DC
    vram: 0x801C46DC
    subsegments:
      - [0x21DC, data, E376_data]

  - [0x8F6C]
