name: E401.BIN
sha1: 4cd27142ba04973a88256801e678e495eb58dda8
options:
  basename: E401.BIN
  target_path: rom/extracted/baserom/EFFECT/E401.BIN
  elf_path: build/blobs/effect_E401/effect_E401.elf
  base_path: ../../..
  platform: psx
  compiler: PSYQ

  asm_path: rom/extracted/blobs/effect
  src_path: src/blobs/effect
  build_path: build/blobs/effect_E401

  ld_script_path: build/blobs/effect_E401/effect_E401.ld
  ld_dependencies: True
  ld_align_section_vram_end: False

  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/blobs/effect/E401.symbols.txt

  undefined_funcs_auto_path: build/blobs/effect_E401/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/blobs/effect_E401/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

family: effect

segments:
  - name: E401
    type: code
    align: 0
    start: 0x0
    vram: 0x801C2500
    subsegments:
      - [0x0, c, E401]

  - name: E401_data
    type: data
    align: 0
    start: 0x21DC
    vram: 0x801C46DC
    subsegments:
      - [0x21DC, data, E401_data]

  - [0xBB48]
