name: E402.BIN
sha1: 7a225905b08507e305dbdae29ede10b47e2a9ea8
options:
  basename: E402.BIN
  target_path: rom/extracted/baserom/EFFECT/E402.BIN
  elf_path: build/blobs/effect_E402/effect_E402.elf
  base_path: ../../..
  platform: psx
  compiler: PSYQ

  asm_path: rom/extracted/blobs/effect
  src_path: src/blobs/effect
  build_path: build/blobs/effect_E402

  ld_script_path: build/blobs/effect_E402/effect_E402.ld
  ld_dependencies: True
  ld_align_section_vram_end: False

  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/blobs/effect/E402.symbols.txt

  undefined_funcs_auto_path: build/blobs/effect_E402/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/blobs/effect_E402/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

family: effect

segments:
  - name: E402
    type: code
    align: 0
    start: 0x0
    vram: 0x801C2500
    subsegments:
      - [0x0, c, E402]

  - name: E402_data
    type: data
    align: 0
    start: 0x1FA0
    vram: 0x801C44A0
    subsegments:
      - [0x1FA0, data, E402_data]

  - [0xD1DC]
