name: E411.BIN
sha1: 36d8a0e707e61349bcfb95a78ced13ea913fd2c2
options:
  basename: E411.BIN
  target_path: rom/extracted/baserom/EFFECT/E411.BIN
  elf_path: build/blobs/effect_E411/effect_E411.elf
  base_path: ../../..
  platform: psx
  compiler: PSYQ

  asm_path: rom/extracted/blobs/effect
  src_path: src/blobs/effect
  build_path: build/blobs/effect_E411

  ld_script_path: build/blobs/effect_E411/effect_E411.ld
  ld_dependencies: True
  ld_align_section_vram_end: False

  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/blobs/effect/E411.symbols.txt

  undefined_funcs_auto_path: build/blobs/effect_E411/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/blobs/effect_E411/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

family: effect

segments:
  - name: E411
    type: code
    align: 0
    start: 0x0
    vram: 0x801C2500
    subsegments:
      - [0x0, c, E411]

  - name: E411_data
    type: data
    align: 0
    start: 0x1354
    vram: 0x801C3854
    subsegments:
      - [0x1354, data, E411_data]

  - [0xC4C4]
