name: E412.BIN
sha1: c440eb3366cee88b9353781db9a11f9f11a38909
options:
  basename: E412.BIN
  target_path: rom/extracted/baserom/EFFECT/E412.BIN
  elf_path: build/blobs/effect_E412/effect_E412.elf
  base_path: ../../..
  platform: psx
  compiler: PSYQ

  asm_path: rom/extracted/blobs/effect
  src_path: src/blobs/effect
  build_path: build/blobs/effect_E412

  ld_script_path: build/blobs/effect_E412/effect_E412.ld
  ld_dependencies: True
  ld_align_section_vram_end: False

  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/blobs/effect/E412.symbols.txt

  undefined_funcs_auto_path: build/blobs/effect_E412/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/blobs/effect_E412/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

family: effect

segments:
  - name: E412
    type: code
    align: 0
    start: 0x0
    vram: 0x801C2500
    subsegments:
      - [0x0, c, E412]

  - name: E412_data
    type: data
    align: 0
    start: 0x2714
    vram: 0x801C4C14
    subsegments:
      - [0x2714, data, E412_data]

  - [0xDB48]
