name: E454.BIN
sha1: 0bc5fc6482c7544379027c118f08846eb2e6a584
options:
  basename: E454.BIN
  target_path: rom/extracted/baserom/EFFECT/E454.BIN
  elf_path: build/blobs/effect_E454/effect_E454.elf
  base_path: ../../..
  platform: psx
  compiler: PSYQ

  asm_path: rom/extracted/blobs/effect
  src_path: src/blobs/effect
  build_path: build/blobs/effect_E454

  ld_script_path: build/blobs/effect_E454/effect_E454.ld
  ld_dependencies: True
  ld_align_section_vram_end: False

  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/blobs/effect/E454.symbols.txt

  undefined_funcs_auto_path: build/blobs/effect_E454/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/blobs/effect_E454/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

family: effect

segments:
  - name: E454
    type: code
    align: 0
    start: 0x0
    vram: 0x801C2504
    subsegments:
      - [0x0, c, E454]

  - name: E454_data
    type: data
    align: 0
    start: 0x23DC
    vram: 0x801C48E0
    subsegments:
      - [0x23DC, data, E454_data]

  - [0xEB8C]
