name: E463.BIN
sha1: 5c0545bb418ac289a5c2bf3cf58bb889189fa7ea
options:
  basename: E463.BIN
  target_path: rom/extracted/baserom/EFFECT/E463.BIN
  elf_path: build/blobs/effect_E463/effect_E463.elf
  base_path: ../../..
  platform: psx
  compiler: PSYQ

  asm_path: rom/extracted/blobs/effect
  src_path: src/blobs/effect
  build_path: build/blobs/effect_E463

  ld_script_path: build/blobs/effect_E463/effect_E463.ld
  ld_dependencies: True
  ld_align_section_vram_end: False

  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/blobs/effect/E463.symbols.txt

  undefined_funcs_auto_path: build/blobs/effect_E463/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/blobs/effect_E463/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

family: effect

segments:
  - name: E463
    type: code
    align: 0
    start: 0x0
    vram: 0x801C2500
    subsegments:
      - [0x0, c, E463]

  - name: E463_data
    type: data
    align: 0
    start: 0x4CEC
    vram: 0x801C71EC
    subsegments:
      - [0x4CEC, data, E463_data]

  - [0x11090]
