name: E472.BIN
sha1: 36a99b2bcaa25594d0d8a75696044f4e36d2a67a
options:
  basename: E472.BIN
  target_path: rom/extracted/baserom/EFFECT/E472.BIN
  elf_path: build/blobs/effect_E472/effect_E472.elf
  base_path: ../../..
  platform: psx
  compiler: PSYQ

  asm_path: rom/extracted/blobs/effect
  src_path: src/blobs/effect
  build_path: build/blobs/effect_E472

  ld_script_path: build/blobs/effect_E472/effect_E472.ld
  ld_dependencies: True
  ld_align_section_vram_end: False

  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/blobs/effect/E472.symbols.txt

  undefined_funcs_auto_path: build/blobs/effect_E472/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/blobs/effect_E472/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

family: effect

segments:
  - name: E472
    type: code
    align: 0
    start: 0x0
    vram: 0x801C2500
    subsegments:
      - [0x0, c, E472]

  - name: E472_data
    type: data
    align: 0
    start: 0x195C
    vram: 0x801C3E5C
    subsegments:
      - [0x195C, data, E472_data]

  - [0xD268]
