name: E473.BIN
sha1: e2bbb4efd585ff235f21251048369f31f7d4df79
options:
  basename: E473.BIN
  target_path: rom/extracted/baserom/EFFECT/E473.BIN
  elf_path: build/blobs/effect_E473/effect_E473.elf
  base_path: ../../..
  platform: psx
  compiler: PSYQ

  asm_path: rom/extracted/blobs/effect
  src_path: src/blobs/effect
  build_path: build/blobs/effect_E473

  ld_script_path: build/blobs/effect_E473/effect_E473.ld
  ld_dependencies: True
  ld_align_section_vram_end: False

  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/blobs/effect/E473.symbols.txt

  undefined_funcs_auto_path: build/blobs/effect_E473/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/blobs/effect_E473/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

family: effect

segments:
  - name: E473
    type: code
    align: 0
    start: 0x0
    vram: 0x801C2500
    subsegments:
      - [0x0, c, E473]

  - name: E473_data
    type: data
    align: 0
    start: 0x77C
    vram: 0x801C2C7C
    subsegments:
      - [0x77C, data, E473_data]

  - [0xC974]
