name: E482.BIN
sha1: cb92c5b317459c3920f7e8b90d403302845993e1
options:
  basename: E482.BIN
  target_path: rom/extracted/baserom/EFFECT/E482.BIN
  elf_path: build/blobs/effect_E482/effect_E482.elf
  base_path: ../../..
  platform: psx
  compiler: PSYQ

  asm_path: rom/extracted/blobs/effect
  src_path: src/blobs/effect
  build_path: build/blobs/effect_E482

  ld_script_path: build/blobs/effect_E482/effect_E482.ld
  ld_dependencies: True
  ld_align_section_vram_end: False

  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/blobs/effect/E482.symbols.txt

  undefined_funcs_auto_path: build/blobs/effect_E482/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/blobs/effect_E482/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

family: effect

segments:
  - name: E482
    type: code
    align: 0
    start: 0x0
    vram: 0x801C2500
    subsegments:
      - [0x0, c, E482]

  - name: E482_data
    type: data
    align: 0
    start: 0x77C
    vram: 0x801C2C7C
    subsegments:
      - [0x77C, data, E482_data]

  - [0x7E7C]
