name: BUNIT.OUT
sha1: 7eaf25ae264dcec456e348ff9065c7ead3f39756
options:
  basename: BUNIT.OUT
  target_path: rom/extracted/baserom/EVENT/BUNIT.OUT
  elf_path: build/blobs/event_BUNIT/event_BUNIT.elf
  base_path: ../../..
  platform: psx
  compiler: PSYQ

  asm_path: rom/extracted/blobs/event
  src_path: src/blobs/event
  build_path: build/blobs/event_BUNIT

  ld_script_path: build/blobs/event_BUNIT/event_BUNIT.ld
  ld_dependencies: True
  ld_align_section_vram_end: False

  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/blobs/event/BUNIT.symbols.txt

  undefined_funcs_auto_path: build/blobs/event_BUNIT/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/blobs/event_BUNIT/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

family: event

segments:
  - name: BUNIT_hdr
    type: data
    align: 0
    start: 0x0
    vram: 0x80060000
    subsegments:
      - [0x0, data, BUNIT_hdr]

  - name: BUNIT
    type: code
    align: 0
    start: 0x20C
    vram: 0x8006020C
    subsegments:
      - [0x20C, c, BUNIT]

  - name: BUNIT_data
    type: data
    align: 0
    start: 0xF8C8
    vram: 0x8006F8C8
    subsegments:
      - [0xF8C8, data, BUNIT_data]

  - [0x2DBB4]
