name: CARD.OUT
sha1: 1353ac09077344e727362ec6c0e7588697ec4cb9
options:
  basename: CARD.OUT
  target_path: rom/extracted/baserom/EVENT/CARD.OUT
  elf_path: build/blobs/event_CARD/event_CARD.elf
  base_path: ../../..
  platform: psx
  compiler: PSYQ

  asm_path: rom/extracted/blobs/event
  src_path: src/blobs/event
  build_path: build/blobs/event_CARD

  ld_script_path: build/blobs/event_CARD/event_CARD.ld
  ld_dependencies: True
  ld_align_section_vram_end: False

  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/blobs/event/CARD.symbols.txt

  undefined_funcs_auto_path: build/blobs/event_CARD/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/blobs/event_CARD/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

family: event

segments:
  - name: CARD_hdr
    type: data
    align: 0
    start: 0x0
    vram: 0x80060000
    subsegments:
      - [0x0, data, CARD_hdr]

  - name: CARD
    type: code
    align: 0
    start: 0x170
    vram: 0x80060170
    subsegments:
      - [0x170, c, CARD]

  - name: CARD_data
    type: data
    align: 0
    start: 0x967C
    vram: 0x8006967C
    subsegments:
      - [0x967C, data, CARD_data]

  - [0x1A2FC]
