#!/usr/bin/env bash
# Self-contained MIPS/PSYQ toolchain bootstrap for the FFT (USA) PSX decomp.
#
# Downloads GCC 2.6.0-psx (decompals/old-gcc) and builds binutils 2.38 for
# mipsel-none-elf directly into tools/toolchain/bin/. Everything lives under
# tools/; no sudo, no PATH edits. Idempotent.
#
# Usage:
#   ./tools/get_toolchain.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TOOLS="$ROOT/tools"
TOOLCHAIN="$TOOLS/toolchain"
TOOLCHAIN_BIN="$TOOLCHAIN/bin"

GCC_VERSION="2.6.0-psx"
GCC_RELEASE="0.17"
GCC_BASE="https://github.com/decompals/old-gcc/releases/download/$GCC_RELEASE"

BINUTILS_VERSION="2.38"
BINUTILS_URL="https://ftp.gnu.org/gnu/binutils/binutils-$BINUTILS_VERSION.tar.xz"

TARGET="mipsel-none-elf"
JOBS="${JOBS:-$(nproc)}"

say() { printf '\033[1;32m[toolchain]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[toolchain]\033[0m error: %s\n' "$*" >&2; exit 1; }

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

mkdir -p "$TOOLCHAIN_BIN"

# --- 1. GCC 2.6.0-psx (directly into toolchain/bin) -------------------------
GCC_BIN="$TOOLCHAIN_BIN/$TARGET-gcc"
if [ -x "$GCC_BIN" ] && "$GCC_BIN" --version 2>/dev/null | grep -q "2\.6\.0"; then
    say "gcc $GCC_VERSION already installed ($GCC_BIN)"
else
    say "downloading gcc-$GCC_VERSION.tar.gz"
    GCC_TAR="$TMPDIR/gcc-$GCC_VERSION.tar.gz"
    curl -fL --retry 3 --connect-timeout 30 -o "$GCC_TAR" "$GCC_BASE/gcc-$GCC_VERSION.tar.gz"
    TMPEXTRACT="$TMPDIR/gcc-extract"
    mkdir -p "$TMPEXTRACT"
    tar -xzf "$GCC_TAR" -C "$TMPEXTRACT"
    say "installing gcc $GCC_VERSION to $TOOLCHAIN_BIN"
    # tarball contains flat files: gcc, g++, cpp, cc1, cc1plus
    for f in gcc g++ cpp cc1 cc1plus; do
        if [ -f "$TMPEXTRACT/$f" ]; then
            cp -f "$TMPEXTRACT/$f" "$TOOLCHAIN_BIN/$f"
            chmod +x "$TOOLCHAIN_BIN/$f"
        fi
    done
    # Wrapper for mipsel-none-elf-gcc: old GCC needs -B to find cc1/cpp
    cat > "$TOOLCHAIN_BIN/$TARGET-gcc" <<WRAP
#!/usr/bin/env bash
# Generated by get_toolchain.sh ($GCC_VERSION). Do not edit.
GCCBIN="$TOOLCHAIN_BIN/gcc"
exec "\$GCCBIN" -B "$TOOLCHAIN_BIN/" "\$@"
WRAP
    chmod +x "$TOOLCHAIN_BIN/$TARGET-gcc"
    cat > "$TOOLCHAIN_BIN/$TARGET-g++" <<WRAP
#!/usr/bin/env bash
GCCBIN="$TOOLCHAIN_BIN/g++"
exec "\$GCCBIN" -B "$TOOLCHAIN_BIN/" "\$@"
WRAP
    chmod +x "$TOOLCHAIN_BIN/$TARGET-g++"
    # cpp wrapper not needed but keep for consistency
    ln -sf cpp "$TOOLCHAIN_BIN/$TARGET-cpp" 2>/dev/null || true
    if ! "$TOOLCHAIN_BIN/$TARGET-gcc" --version 2>/dev/null | grep -q "2\.6\.0"; then
        die "gcc install failed ($GCC_BIN --version did not report 2.6.0)"
    fi
    rm -rf "$TMPEXTRACT" "$GCC_TAR"
fi

# --- 1b. GCC 2.7.2-psx (Sony PSYQ-fork lineage, FSF build) --------------------
# A second cc1 for blob translation units the original built with Sony's
# PSYQ fork (GNU C 2.7.2.SN.1): native FSF 2.7.2-psx reproduces its codegen
# exactly on the proven shapes (filled live `j` delay slots from the
# trailing-store schedule; FSF 2.6.0 provably cannot). Kept in its own
# prefix so it never collides with the pinned 2.6.0 toolchain above.
# Consumed per-C-unit via Makefile FORK_* overrides (see FORK_SRCS).
GCC272_VERSION="2.7.2-psx"
GCC272_PREFIX="$TOOLCHAIN/gcc-$GCC272_VERSION"
GCC272_BIN="$GCC272_PREFIX/bin/mipsel-none-elf-gcc"
if [ -x "$GCC272_BIN" ] && "$GCC272_BIN" --version 2>/dev/null | grep -q "2\.7\.2"; then
    say "gcc $GCC272_VERSION already installed ($GCC272_BIN)"
else
    say "downloading gcc-$GCC272_VERSION.tar.gz"
    GCC272_TAR="$TMPDIR/gcc-$GCC272_VERSION.tar.gz"
    curl -fL --retry 3 --connect-timeout 30 -o "$GCC272_TAR" "$GCC_BASE/gcc-$GCC272_VERSION.tar.gz"
    mkdir -p "$GCC272_PREFIX/bin"
    say "installing gcc $GCC272_VERSION to $GCC272_PREFIX/bin"
    # tarball contains flat files: gcc, g++, cpp, cc1, cc1plus
    tar -xzf "$GCC272_TAR" -C "$GCC272_PREFIX/bin"
    for f in gcc g++ cpp cc1 cc1plus; do
        chmod +x "$GCC272_PREFIX/bin/$f" 2>/dev/null || true
    done
    # Wrapper for mipsel-none-elf-gcc: old GCC needs -B to find cc1/cpp
    cat > "$GCC272_BIN" <<WRAP
#!/usr/bin/env bash
# Generated by get_toolchain.sh ($GCC272_VERSION). Do not edit.
GCCBIN="$GCC272_PREFIX/bin/gcc"
exec "\$GCCBIN" -B "$GCC272_PREFIX/bin/" "\$@"
WRAP
    chmod +x "$GCC272_BIN"
    if ! "$GCC272_BIN" --version 2>/dev/null | grep -q "2\.7\.2"; then
        die "gcc install failed ($GCC272_BIN --version did not report 2.7.2)"
    fi
    rm -rf "$GCC272_TAR"
fi

# --- 2. build GNU binutils directly into toolchain --------------------------
BINUTILS_AS="$TOOLCHAIN_BIN/$TARGET-as"
if [ -x "$BINUTILS_AS" ]; then
    say "binutils already built ($BINUTILS_AS)"
else
    BINUTILS_TAR="$TMPDIR/binutils-$BINUTILS_VERSION.tar.xz"
    say "downloading binutils-$BINUTILS_VERSION"
    curl -fL --retry 3 --connect-timeout 30 -o "$BINUTILS_TAR" "$BINUTILS_URL"
    BINUTILS_SRC="$TMPDIR/binutils-src"
    mkdir -p "$BINUTILS_SRC"
    say "extracting binutils-$BINUTILS_VERSION"
    tar -xJf "$BINUTILS_TAR" -C "$BINUTILS_SRC" --strip-components=1
    say "building binutils-$BINUTILS_VERSION for $TARGET (this takes a few minutes)"
    BINUTILS_BUILD="$TMPDIR/binutils-build"
    mkdir -p "$BINUTILS_BUILD"
    cd "$BINUTILS_SRC"
    BINUTILS_CFLAGS="-O2 -g -std=gnu17 -Ustatic_assert"
    ./configure --target="$TARGET" --prefix="$TOOLCHAIN" \
        --disable-nls --disable-werror --disable-gdb --disable-gprof \
        --disable-gas-doc --disable-ld-doc >/dev/null
    make -s -j"$JOBS" CFLAGS="$BINUTILS_CFLAGS" all-gas all-ld all-binutils
    make -s CFLAGS="$BINUTILS_CFLAGS" install-gas install-ld install-binutils
    cd "$ROOT"
    rm -rf "$BINUTILS_SRC" "$BINUTILS_BUILD" "$BINUTILS_TAR"
fi

# symlink stable names regardless of target prefix
for tool in as ld objcopy objdump; do
    if [ -x "$TOOLCHAIN_BIN/$TARGET-$tool" ] && [ ! -e "$TOOLCHAIN_BIN/$tool" ]; then
        ln -sf "$TARGET-$tool" "$TOOLCHAIN_BIN/$tool"
    fi
done

# --- 3. report --------------------------------------------------------------
say "installed. Resolved toolchain paths:"
printf '  MIPS_GCC : %s\n' "$TOOLCHAIN_BIN/$TARGET-gcc"
"$TOOLCHAIN_BIN/$TARGET-gcc" --version 2>/dev/null | head -n1 | sed 's/^/    /'
printf '  MIPS_AS  : %s\n' "$BINUTILS_AS"
printf '  MIPS_LD  : %s\n' "$TOOLCHAIN_BIN/$TARGET-ld"
printf '  OBJCOPY  : %s\n' "$TOOLCHAIN_BIN/$TARGET-objcopy"
